import assert from 'node:assert/strict'
import test from 'node:test'
import {chromium} from './helpers/chromium.mjs'
import {loadPluginInternals} from './helpers/load-plugin.mjs'
test('artifact close control, icon and filename center within compact Codex row',async()=>{
 const b=await chromium()
 try{
 const {CSS}=await loadPluginInternals(['CSS']);const {frameTree}=await b.call('Page.getFrameTree')
 await b.call('Page.setDocumentContent',{frameId:frameTree.frame.id,html:`<html data-codex-chat-look="true"><head><style>
*{box-sizing:border-box}body{margin:0;font:12px sans-serif}.status-row{display:grid;grid-template-columns:12px 13px minmax(0,1fr) auto;align-items:start;gap:6px;padding:4px 10px;min-height:24px;width:400px}.status-row-dismiss{grid-column:1;grid-row:1;display:flex;justify-content:center;height:16px}.status-dismiss-button{display:inline-flex;align-items:center;justify-content:center;width:16px;height:16px;border:0;margin:0;padding:0}.status-row-icon{grid-column:2;grid-row:1;width:13px;height:16px;display:flex;align-items:center;justify-content:center}.status-row-content{grid-column:3;grid-row:1;display:flex;align-items:start;min-width:0;line-height:16px}.status-row-content>span{white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.status-artifacts>.status-row:first-child{padding-top:6px}.status-artifacts>.status-row:last-child{padding-bottom:6px}${CSS}</style></head><body><div data-slot="composer-status-stack"><div data-codex-status-card="true"><div class="status-artifacts"><div id="row" class="group/status-row status-row" data-slot="status-row" role="button"><span class="status-row-dismiss"><button id="close" class="status-dismiss-button" data-slot="status-dismiss" aria-label="Dismiss">×</button></span><span class="status-row-icon" id="icon">◎</span><div class="status-row-content"><span id="name">index.html</span></div></div></div><div id="queue" class="group/status-row status-row" data-slot="status-row"><span class="status-row-dismiss">×</span><div class="status-row-content">A multiline<br>queued prompt</div></div></div></div></body></html>`})
 const r=await b.evaluate(`(()=>{const row=document.getElementById('row');let opened=0,closed=0;row.onclick=()=>opened++;document.getElementById('close').onclick=e=>{e.stopPropagation();closed++};const measure=()=>{const rr=row.getBoundingClientRect();return ['close','icon','name'].map(id=>{const r=document.getElementById(id).getBoundingClientRect();return {id,delta:(r.top+r.bottom-rr.top-rr.bottom)/2,hit:document.elementFromPoint((r.left+r.right)/2,(r.top+r.bottom)/2)?.id}})};const normal=measure();row.style.width='130px';document.getElementById('name').textContent='very-long-generated-preview-file.html';const narrow=measure();document.getElementById('close').click();const queue=getComputedStyle(document.getElementById('queue')).alignItems;document.documentElement.removeAttribute('data-codex-chat-look');return{normal,narrow,opened,closed,queue,disabled:getComputedStyle(row).alignItems}})()`)
 for(const state of [r.normal,r.narrow])for(const e of state)assert.ok(Math.abs(e.delta)<.6,JSON.stringify(e))
 assert.equal(r.normal[0].hit,'close');assert.equal(r.narrow[0].hit,'close');assert.equal(r.closed,1);assert.equal(r.opened,0);assert.equal(r.queue,'start');assert.equal(r.disabled,'start')
 }finally{b.close()}
})
